//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXBlueStarGroup_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string RowID { get; set; }
        public long ID { get; set; }
        public string DateName { get; set; }
        public string CompanyID { get; set; }
        public string Name { get; set; }
        public string SummaryName { get; set; }
        public string Address { get; set; }
        public string MST { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string AccountBank { get; set; }
        public string Bank { get; set; }
        public string BranchBank { get; set; }
        public string Logo { get; set; }
        public string BackGround { get; set; }
        public string StampCircel { get; set; }
        public string StampSquare { get; set; }
        public string SoQuyetDinh { get; set; }
        public string MaSoHD { get; set; }
        public string NoiQLThue { get; set; }
        public string NHKhoBac { get; set; }
        public string TKThuThue { get; set; }
        public string LapBieu { get; set; }
        public string KTTruong { get; set; }
        public string KTVien { get; set; }
        public string LanhDao { get; set; }
        public string ThuQuy { get; set; }
        public string ChucDanhLanhDao { get; set; }
        public string ChukyLapBieu { get; set; }
        public string ChuKyKTTruong { get; set; }
        public string ChuKyKeToanVien { get; set; }
        public string ChuKyLanhDao { get; set; }
        public string ChuKyThuQuy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public string Status { get; set; }
    }
}
