//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXBlueStarGroup_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationDetail
    {
        public string RowID { get; set; }
        public long ID { get; set; }
        public string DateName { get; set; }
        public string DepreciationID { get; set; }
        public string InvoiceDetailID { get; set; }
        public string WareHouseDetailID { get; set; }
        public Nullable<int> PeriodCurrent { get; set; }
        public Nullable<System.DateTime> DepreciationDate { get; set; }
        public Nullable<int> QuantityPeriod { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public string Status { get; set; }
        public string CompanyID { get; set; }
    }
}
