//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXBlueStarGroup_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestID
    {
        public string RowID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public long ID { get; set; }
        public string DateName { get; set; }
        public string UserID { get; set; }
    }
}
