//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXBlueStarGroup_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouseDetail
    {
        public string RowID { get; set; }
        public long ID { get; set; }
        public string DateName { get; set; }
        public string WareHouseDetailID { get; set; }
        public string VouchersDetailID { get; set; }
        public string CustomerID { get; set; }
        public string ItemID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<int> UseMonth { get; set; }
        public Nullable<int> DepreciationMonth { get; set; }
        public Nullable<int> CurrentMonth { get; set; }
        public Nullable<decimal> DepreciationAmount { get; set; }
        public Nullable<decimal> DepreciationPercent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public string Status { get; set; }
        public string CompanyID { get; set; }
    }
}
