
alter proc InvoiceInsert
	@InvoiceID varchar(50),
	@VouchersID varchar(50) ,
	@CustomerID varchar(50) ,
	@Description nvarchar(max) ,
	@MaSo varchar(50) ,
	@MauSo varchar(50) ,
	@KyHieu varchar(50) ,
	@InvoiceNo varchar(50) ,
	@InvoiceType varchar(1) ,
	@InvoiceDate datetime ,
	@Amount money ,
	@VAT decimal ,
	@Discounts money ,
	@CreateUser varchar(50) ,
	@CompanyID varchar(50),
	@PaymentType varchar(2),
    @S35Type bit,
    @InvoiceAccountID varchar(50),
    @InvoiceAccountDetailID varchar(50),
    @InvoiceVATAccountID varchar(50),
	@MST varchar(50),
    @CustomerName varchar(250)
as
begin
INSERT INTO Invoice(
	InvoiceID,
	VouchersID,
	CustomerID,
	Description,
	InvoiceFormNo,
	FormNo,
	SerialNo,
	InvoiceNo,
	InvoiceType,
	InvoiceDate,
	Amount,
	VAT,
	Discounts,
	CreateDate,
	CreateUser,
	CompanyID,
	PaymentType,
    S35Type,
    InvoiceAccountID,
    InvoiceAccountDetailID,
    InvoiceVATAccountID,
	MST,
    CustomerName
	)
	VALUES(
	@InvoiceID,
	@VouchersID,
	@CustomerID,
	@Description,
	@MaSo,
	@MauSo,
	@KyHieu,
	@InvoiceNo,
	@InvoiceType,
	@InvoiceDate,
	@Amount,
	@VAT,
	@Discounts,
	getdate(),
	@CreateUser,
	@CompanyID,
	@PaymentType,
    @S35Type,
    @InvoiceAccountID,
    @InvoiceAccountDetailID,
    @InvoiceVATAccountID,
	@MST,
    @CustomerName
	)
end